server:
  port: 8080

kafka:
  producer:
    bootstrap: localhost:9092
    topic: workunits

spring:
  application:
    name: sample-producer
  sleuth:
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka:
        binder:
          headers:
            - X-B3-TraceId
            - X-B3-SpanId
            - X-B3-Sampled
            - X-B3-ParentSpanId
            - X-Span-Name
            - X-Span-Export